server:
  port: 8080
  servlet:
    context-path: /mall
nacos:
  config:
    server-addr: 47.94.132.120:8848
    namespace: 734e958c-3ce7-4652-8f8a-abec6c446d1f
#    prefix: ${spring.application.name}
#    file-extension: yml
spring:
  profiles:
    active: dev
  application:
    name: mall
  cloud:
    # nacos 配置
    nacos:
      discovery:
        server-addr: 47.94.132.120:8848 # 配置nacos地址
#spring:
#  application:
#    name: mall
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.94.132.120:8848
#      config:
#        server-addr: 47.94.132.120:8848
#        prefix: ${spring.application.name}
#        file-extension: yml
#        namespace: 734e958c-3ce7-4652-8f8a-abec6c446d1f


#暴露端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    data:
#      elasticsearch:
#        repositories:
#          enabled: true
#        cluster-name: elasticsearch
#          address: 123.57.2.37
#          port: 9300
#        cluster-nodes: 123.57.2.37:9300 # es的连接地址及端口号
#        cluster-name: elasticsearch # es集群的名称

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml
  # 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


