spring:
    profiles:
      active: dev
    datasource:
      druid:
        initial-size: 10
        min-idle: 6
        max-active: 50
        max-wait: 60000

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml
 # 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头